"""Add category and attachments fields to Property model

Revision ID: 5ff3b7e6ff31
Revises: 
Create Date: 2024-03-02 14:44:01.542121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ff3b7e6ff31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('attachments', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('size', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))
        batch_op.alter_column('created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('is_available')
        batch_op.drop_column('size')
        batch_op.drop_column('attachments')
        batch_op.drop_column('location')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
